fix eager load on zeitwerk
cookpad/chanko pull request #64
Opened 2022-11-19 07:49 UTC by eudoxa

# developmentモードでの動作処理およびコードを確認しつつ加筆予定

# 現状
Rails6以上のzeitwerkを利用した環境ではproductionのeager_loadが正しく機能せず、Unitの読み込みでNameErrorが発生します。

# 調査
### zeitwerkではinitializer("chanko.eager_load_units")でautoload_pathsを追加しません。また、このタイミングではzeitwerk読み込みが機能しないため、その後のconstantizeに失敗します。

また、そもそもとして、zeitwerkのeager_loadでは下記のコードでサブディレクトリまで対応しているため、明示的な処理は不要です。
https://github.com/fxn/zeitwerk/blob/main/lib/zeitwerk/loader/eager_load.rb#L164-L179

2022-11-24 21:48 UTC, r7kamura commented
> Rails6以上のzeitwerkを利用した環境ではproductionのeager_loadが正しく機能せず、Unitの読み込みでNameErrorが発生する。

という問題への対策を入れようとしているので、eager_loadが有効化された状態でUnitが読み込めることが保証されるテストになっていると良いと思いました。

テスト時もeager_loadを有効化しておくのはどうでしょうか？最近のRailsの雛形だとtest環境で `config.eager_load = ENV['CI'].present?` となっているので、テスト時にeager_loadを有効化しておくことは不自然ではないと思います。

実際にeager_loadを有効化してみると、Unitが正常に読み込まれずRSpecが失敗するように見える (Unitの定数を探索しようとして `NameError` が起きる) ので、何かまだ実装に問題があるか、あるいはテストでの設定に不足があるかもしれません。

2022-11-25 00:03 UTC, eudoxa commented
ありがとうございます。EagerLoadの有り無しのテストはどうやって書くか悩んでいたところでした。eager load = trueのみのテストにすると、今度は開発モードのバグが残ってしまうので、両方をテストできる方法を考えますね。

2022-11-25 01:46 UTC, eudoxa commented
一旦Draftに戻します。

2022-11-25 06:05 UTC, eudoxa commented
環境変数EAGER_LOADとAUTOLOADERでテスト環境を切り替えられるようにしつつ、修正をしたためReady for reviewに戻します。

自分のリポジトリでのテストの実行結果: https://github.com/eudoxa/chanko/actions/runs/3545675156/jobs/5953996245

2022-11-25 08:27 UTC, eudoxa commented on spec/chanko/invoker_spec.rb
> +      controller.helpers
ViewとControllerで共有すべきではないLookupContextのキャッシュを共有している事への対応として変更しましたが、LookupContextのCacheを無効化する対応ができるかもしれないので少し調べます。

2022-11-26 00:46 UTC, r7kamura commented
ReadonlyなCollaboratorの観点でレビューすると、コード的には全体的にかなり良さそうでした。

普通のOSSのライブラリとして見ると下記の点が気になりましたが、この辺りは運用する側のポリシーや労力の掛け方に大きく依存する話だと思うので、Memberの意見次第だと思っています。

- 互換性をどの程度気にするか
    - 例えば `eager_load` の設定項目は外部から利用されている可能性が高いが、ここで廃止することを良しとするのか
    - テスト対象のRubyとRailsのバージョンの選定基準はこれで良いのか
    - 次回のリリースはバージョンをどれくらい変更すべきか
- Pull Requestの粒度はこれで良いか
    - 上の互換性の話を細かくやりたいなら、変更を分けて個々のPull Requestで議論できるようにした方が良いかもしれない
    - 分けるのは正直かなり面倒そう

個人的には、cookpadの内部で上手く動くなら現状このPull Requestの対応で十分だろうと思っています。

2022-11-28 01:51 UTC, eudoxa commented
ありがとうございます。粒度に関しては仰るとおりなのですが、動いていない状態を直しながらのテスト整備のため分離は工数的に難しいところでした。指摘の点についての考えをログとして理由を書いておきます。

> 例えば eager_load の設定項目は外部から利用されている可能性が高いが、ここで廃止することを良しとするのか
eager_load

2022-11-28 09:10 UTC, uasi submitted a review, later dismissed
Workflow を動かすために仮で approve します。

2022-11-28 18:05 UTC, uasi requested changes

2022-11-28 18:05 UTC, uasi commented on lib/chanko/loader.rb
> +        if Rails.configuration.eager_load
テスト実行時、 `EAGER_LOAD=true` してもしなくてもここの `Rails.configuration.eager_load` が nil になって以下のコードが実行されません。

2022-11-28 18:34 UTC, uasi commented
> cookpad/chankoでは実行されないようなので、Settingsを見られる方に有効かどうか確認をしていただきたいです。

設定では有効になっています。 master に .github/workflows ない場合 fork から送った PR では workflow が動かない気がします。

2022-11-29 05:12 UTC, eudoxa commented on lib/chanko/loader.rb
> +        if Rails.configuration.eager_load
ありがとうございます。environmentsのinitializerがset_autoload_pathより後ろに来ていました。対応方法を考えます。
https://railsguides.jp/configuring.html

2022-11-29 12:21 UTC, eudoxa commented
Rails5, 6(classic), 6(zeitwerk)の挙動を確認したところ下記の通りだっため、Initializerのタイミングをそれぞれに分けました。 https://github.com/cookpad/chanko/pull/64/commits/ff4b332e50851a99351c57e20f923114ffb18b76

また、問題を検知出来るように、config.eager_loadがnilの状態では例外を出すように変更しました。

---
**Rails5**
- before set_autoload_pathsではconfig.eager_loadが参照不可能(未設定)
- set_autoload_pathsでpathsをfreezeしない

**Rails6.0 & classic**
- before set_autoload_pathsではconfig.eager_loadが参照不可能(未設定)
- set_autoload_pathsでpathsをfreezeしない

**Rails.6.1 & classic**
- before set_autoload_pathsでconfig.eager_loadが参照可能(設定済み)
- set_autoload_pathsでpathsをfreezeしない

**Rails6.0 & zeitwerk**
- before set_autoload_pathsではconfig.eager_loadが参照不可能(未設定)
- set_autoload_pathsでpathsをfreezeする

**Rails.6.1 & zeitwerk**
- before set_autoload_pathsでconfig.eager_loadが参照可能(設定済み)
- set_autoload_pathsでpathsをfreezeする

2022-11-29 12:23 UTC, eudoxa commented
@uasi 
指摘いただいたegar_load=nilの問題について、各バージョンの挙動を確認し、Initializerの実行タイミングを分けました。 https://github.com/cookpad/chanko/pull/64/commits/ff4b332e50851a99351c57e20f923114ffb18b76

また、問題を検知出来るように、config.eager_loadがnilでは例外を出すように変更しました。

---
**Rails5**
- before set_autoload_pathsではconfig.eager_loadが参照不可能(未設定)
- set_autoload_pathsでpathsをfreezeしない

**Rails6.0 & classic**
- before set_autoload_pathsではconfig.eager_loadが参照不可能(未設定)
- set_autoload_pathsでpathsをfreezeしない

**Rails.6.1 & classic**
- before set_autoload_pathsでconfig.eager_loadが参照可能(設定済み)
- set_autoload_pathsでpathsをfreezeしない

**Rails6.0 & zeitwerk**
- before set_autoload_pathsではconfig.eager_loadが参照不可能(未設定)
- set_autoload_pathsでpathsをfreezeする

**Rails.6.1 & zeitwerk**
- before set_autoload_pathsでconfig.eager_loadが参照可能(設定済み)
- set_autoload_pathsでpathsをfreezeする

2022-11-30 02:05 UTC, eudoxa commented on spec/chanko/loader_spec.rb
> +          expect_any_instance_of(Chanko::Loader::ClassicLoader).to receive(:load_from_file).and_call_original
PRが肥大化する中なので、既存の改善については別PRでだしますね。

2022-11-30 02:23 UTC, eudoxa commented on lib/chanko/loader.rb
> +        if Rails.configuration.eager_load
https://github.com/cookpad/chanko/commit/ff4b332e50851a99351c57e20f923114ffb18b76 で対応しました

2022-11-30 03:12 UTC, eudoxa commented on spec/dummy/config/application.rb
> +        Chanko::Test.logger.info("Autoloader: zeitwerk ")
fixed

2022-11-30 03:12 UTC, eudoxa commented on chanko.gemspec
> +  gem.add_development_dependency "pry-rails"
fixed https://github.com/cookpad/chanko/pull/64/commits/dd95d957d00fc63d0b6e8d7700189996e6caa4fa

2022-11-30 03:12 UTC, eudoxa commented on lib/chanko/config.rb
> +      end
fixed https://github.com/cookpad/chanko/pull/64/commits/10f35bf86844a3dd014b4c1a0520ed2020d75458

2022-11-30 03:13 UTC, eudoxa commented on lib/chanko/railtie.rb
> +    initializer "chanko.include", before: "eager_load!" do |app|
fixed https://github.com/cookpad/chanko/pull/64/commits/6921fee117945eb7b613dfbfa3362d5954aadecc

2022-11-30 03:13 UTC, eudoxa commented on lib/chanko/loader.rb
> +          Chanko::Loader::ClassicLoader.load(path.to_s.split("/").last.to_s)
fixed
https://github.com/cookpad/chanko/pull/64/commits/6921fee117945eb7b613dfbfa3362d5954aadecc
https://github.com/cookpad/chanko/pull/64/commits/1d7d68b122f797816f99db2f2bc22648c1559ceb

2022-11-30 06:02 UTC, uasi approved these changes

2022-11-30 06:28 UTC, eudoxa commented
今後の作業
1. merge後のリビジョンでcookpad/chankoにrails6ブランチとして一旦登録
2. READMEの編集を含めてbunmupのPRを作成
3. bumpup依頼(社内対応)

2022-11-30 06:29 UTC, eudoxa commented on lib/chanko/loader.rb
> +    class MissingEagarLoadEsettingError < StandardError; end
woops https://github.com/cookpad/chanko/pull/64/commits/3c7e603612d9b17fd337f1b8265b56a4f7abdc3c

2022-11-30 06:34 UTC, merged